// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/admin/_middleware.ts";
import * as $5 from "./routes/admin/client/index.tsx";
import * as $6 from "./routes/admin/client/register.tsx";
import * as $7 from "./routes/admin/index.tsx";
import * as $8 from "./routes/admin/login.tsx";
import * as $9 from "./routes/admin/owner/empresarial/index.tsx";
import * as $10 from "./routes/admin/owner/empresarial/register.tsx";
import * as $11 from "./routes/admin/owner/index.tsx";
import * as $12 from "./routes/admin/owner/private/index.tsx";
import * as $13 from "./routes/admin/owner/private/register.tsx";
import * as $14 from "./routes/admin/property/index.tsx";
import * as $15 from "./routes/admin/property/register.tsx";
import * as $16 from "./routes/api/_middleware.ts";
import * as $17 from "./routes/api/auth/client/index.ts";
import * as $18 from "./routes/api/auth/client/login.ts";
import * as $19 from "./routes/api/auth/employee/login.ts";
import * as $20 from "./routes/api/dinosaur/[id].ts";
import * as $21 from "./routes/api/dinosaur/index.ts";
import * as $22 from "./routes/api/index.ts";
import * as $23 from "./routes/api/owner/empresarial/index.ts";
import * as $24 from "./routes/api/owner/private/index.ts";
import * as $25 from "./routes/api/property/filter.ts";
import * as $26 from "./routes/api/property/index.ts";
import * as $27 from "./routes/dinosaur/[id]/edit.tsx";
import * as $28 from "./routes/dinosaur/[id]/index.tsx";
import * as $29 from "./routes/dinosaur/index.tsx";
import * as $30 from "./routes/explore.tsx";
import * as $31 from "./routes/index.tsx";
import * as $32 from "./routes/login.tsx";
import * as $33 from "./routes/logout.ts";
import * as $34 from "./routes/property/[id].tsx";
import * as $35 from "./routes/property/index.tsx";
import * as $$0 from "./islands/LoginForm.tsx";
import * as $$1 from "./islands/Slider.tsx";
import * as $$2 from "./islands/client/ListClients.tsx";
import * as $$3 from "./islands/client/NewClientForm.tsx";
import * as $$4 from "./islands/dinosaur/DeleteDinosaurButton.tsx";
import * as $$5 from "./islands/dinosaur/DinosaurList.tsx";
import * as $$6 from "./islands/dinosaur/EditDinosaur.tsx";
import * as $$7 from "./islands/dinosaur/NewDinosaurForm.tsx";
import * as $$8 from "./islands/owner/empresarial/ListOwners.tsx";
import * as $$9 from "./islands/owner/empresarial/NewOwnerForm.tsx";
import * as $$10 from "./islands/owner/private/ListOwners.tsx";
import * as $$11 from "./islands/owner/private/NewOwner.tsx";
import * as $$12 from "./islands/property/FilteredListProperties.tsx";
import * as $$13 from "./islands/property/ListProperties.tsx";
import * as $$14 from "./islands/property/NewProperty.tsx";
import * as $$15 from "./islands/property/SearchPropertiesForm.tsx";
import * as $$16 from "./islands/property/SelectOwner.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/admin/_middleware.ts": $4,
    "./routes/admin/client/index.tsx": $5,
    "./routes/admin/client/register.tsx": $6,
    "./routes/admin/index.tsx": $7,
    "./routes/admin/login.tsx": $8,
    "./routes/admin/owner/empresarial/index.tsx": $9,
    "./routes/admin/owner/empresarial/register.tsx": $10,
    "./routes/admin/owner/index.tsx": $11,
    "./routes/admin/owner/private/index.tsx": $12,
    "./routes/admin/owner/private/register.tsx": $13,
    "./routes/admin/property/index.tsx": $14,
    "./routes/admin/property/register.tsx": $15,
    "./routes/api/_middleware.ts": $16,
    "./routes/api/auth/client/index.ts": $17,
    "./routes/api/auth/client/login.ts": $18,
    "./routes/api/auth/employee/login.ts": $19,
    "./routes/api/dinosaur/[id].ts": $20,
    "./routes/api/dinosaur/index.ts": $21,
    "./routes/api/index.ts": $22,
    "./routes/api/owner/empresarial/index.ts": $23,
    "./routes/api/owner/private/index.ts": $24,
    "./routes/api/property/filter.ts": $25,
    "./routes/api/property/index.ts": $26,
    "./routes/dinosaur/[id]/edit.tsx": $27,
    "./routes/dinosaur/[id]/index.tsx": $28,
    "./routes/dinosaur/index.tsx": $29,
    "./routes/explore.tsx": $30,
    "./routes/index.tsx": $31,
    "./routes/login.tsx": $32,
    "./routes/logout.ts": $33,
    "./routes/property/[id].tsx": $34,
    "./routes/property/index.tsx": $35,
  },
  islands: {
    "./islands/LoginForm.tsx": $$0,
    "./islands/Slider.tsx": $$1,
    "./islands/client/ListClients.tsx": $$2,
    "./islands/client/NewClientForm.tsx": $$3,
    "./islands/dinosaur/DeleteDinosaurButton.tsx": $$4,
    "./islands/dinosaur/DinosaurList.tsx": $$5,
    "./islands/dinosaur/EditDinosaur.tsx": $$6,
    "./islands/dinosaur/NewDinosaurForm.tsx": $$7,
    "./islands/owner/empresarial/ListOwners.tsx": $$8,
    "./islands/owner/empresarial/NewOwnerForm.tsx": $$9,
    "./islands/owner/private/ListOwners.tsx": $$10,
    "./islands/owner/private/NewOwner.tsx": $$11,
    "./islands/property/FilteredListProperties.tsx": $$12,
    "./islands/property/ListProperties.tsx": $$13,
    "./islands/property/NewProperty.tsx": $$14,
    "./islands/property/SearchPropertiesForm.tsx": $$15,
    "./islands/property/SelectOwner.tsx": $$16,
  },
  baseUrl: import.meta.url,
};

export default manifest;
