// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/admin/_middleware.ts";
import * as $3 from "./routes/admin/index.tsx";
import * as $4 from "./routes/admin/login.tsx";
import * as $5 from "./routes/admin/logout.ts";
import * as $6 from "./routes/admin/property/index.tsx";
import * as $7 from "./routes/admin/property/register.tsx";
import * as $8 from "./routes/api/_middleware.ts";
import * as $9 from "./routes/api/auth/employee/login.ts";
import * as $10 from "./routes/api/dinosaur/[id].ts";
import * as $11 from "./routes/api/dinosaur/index.ts";
import * as $12 from "./routes/api/index.ts";
import * as $13 from "./routes/api/owner/empresarial/index.ts";
import * as $14 from "./routes/api/owner/private/index.ts";
import * as $15 from "./routes/api/property/index.ts";
import * as $16 from "./routes/dinosaur/[id]/edit.tsx";
import * as $17 from "./routes/dinosaur/[id]/index.tsx";
import * as $18 from "./routes/dinosaur/index.tsx";
import * as $19 from "./routes/index.tsx";
import * as $$0 from "./islands/LoginForm.tsx";
import * as $$1 from "./islands/dinosaur/DeleteDinosaurButton.tsx";
import * as $$2 from "./islands/dinosaur/DinosaurList.tsx";
import * as $$3 from "./islands/dinosaur/EditDinosaur.tsx";
import * as $$4 from "./islands/dinosaur/NewDinosaurForm.tsx";
import * as $$5 from "./islands/property/ListProperties.tsx";
import * as $$6 from "./islands/property/NewProperty.tsx";
import * as $$7 from "./islands/property/SelectOwner.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/admin/_middleware.ts": $2,
    "./routes/admin/index.tsx": $3,
    "./routes/admin/login.tsx": $4,
    "./routes/admin/logout.ts": $5,
    "./routes/admin/property/index.tsx": $6,
    "./routes/admin/property/register.tsx": $7,
    "./routes/api/_middleware.ts": $8,
    "./routes/api/auth/employee/login.ts": $9,
    "./routes/api/dinosaur/[id].ts": $10,
    "./routes/api/dinosaur/index.ts": $11,
    "./routes/api/index.ts": $12,
    "./routes/api/owner/empresarial/index.ts": $13,
    "./routes/api/owner/private/index.ts": $14,
    "./routes/api/property/index.ts": $15,
    "./routes/dinosaur/[id]/edit.tsx": $16,
    "./routes/dinosaur/[id]/index.tsx": $17,
    "./routes/dinosaur/index.tsx": $18,
    "./routes/index.tsx": $19,
  },
  islands: {
    "./islands/LoginForm.tsx": $$0,
    "./islands/dinosaur/DeleteDinosaurButton.tsx": $$1,
    "./islands/dinosaur/DinosaurList.tsx": $$2,
    "./islands/dinosaur/EditDinosaur.tsx": $$3,
    "./islands/dinosaur/NewDinosaurForm.tsx": $$4,
    "./islands/property/ListProperties.tsx": $$5,
    "./islands/property/NewProperty.tsx": $$6,
    "./islands/property/SelectOwner.tsx": $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
