// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/dinosaur/[id].ts";
import * as $3 from "./routes/api/dinosaur/index.ts";
import * as $4 from "./routes/api/index.ts";
import * as $5 from "./routes/dinosaur/[id]/edit.tsx";
import * as $6 from "./routes/dinosaur/[id]/index.tsx";
import * as $7 from "./routes/dinosaur/index.tsx";
import * as $8 from "./routes/index.tsx";
import * as $$0 from "./islands/dinosaur/DeleteDinosaurButton.tsx";
import * as $$1 from "./islands/dinosaur/DinosaurList.tsx";
import * as $$2 from "./islands/dinosaur/EditDinosaur.tsx";
import * as $$3 from "./islands/dinosaur/NewDinosaurForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/dinosaur/[id].ts": $2,
    "./routes/api/dinosaur/index.ts": $3,
    "./routes/api/index.ts": $4,
    "./routes/dinosaur/[id]/edit.tsx": $5,
    "./routes/dinosaur/[id]/index.tsx": $6,
    "./routes/dinosaur/index.tsx": $7,
    "./routes/index.tsx": $8,
  },
  islands: {
    "./islands/dinosaur/DeleteDinosaurButton.tsx": $$0,
    "./islands/dinosaur/DinosaurList.tsx": $$1,
    "./islands/dinosaur/EditDinosaur.tsx": $$2,
    "./islands/dinosaur/NewDinosaurForm.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
